version: '3.7'

services:
  postgres:
    container_name: rpk_postgres
    image: postgres
    environment:
      POSTGRES_USER: "${POSTGRES_USER:-root}"
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "15432:5432"
    networks:
      - dbs
    restart: unless-stopped
  
  pgadmin:
    container_name: rpk_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-root}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-root}
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "15431:80"
    networks:
      - dbs
    restart: unless-stopped

  my-mongodb:
    image: mongo:latest
    container_name: rpk_mongo
    ports:
      - 47017:27017
    environment:
      - MONGO_INITDB_DATABASE=test
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      # seeding scripts
      - ./mongo-entrypoint:/docker-entrypoint-initdb.d
      # named volumes
      - mongodb:/data/db
      - mongoconfig:/data/configdb
    networks:
      - dbs

networks:
  dbs:
    driver: bridge

volumes:
    postgres:
    pgadmin:
    mongodb:
    mongoconfig: